#!/usr/bin/env bun
// Scans .compositions/<id>/Composition.tsx and writes src/_generated-compositions.ts.
// Run before `remotion studio` / `remotion render` so generated compositions
// show up in the main Studio under a Generated folder.

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const COMPOSITIONS_DIR = join(ROOT, ".compositions");
const OUTPUT = join(ROOT, "src", "_generated-compositions.ts");
const REMOTION_ID_RE = /^[A-Za-z0-9-]+$/;

interface Entry {
  id: string;
  alias: string;
  importPath: string;
  mtimeMs: number;
  title?: string;
  kind?: string;
}

function safeAlias(id: string): string {
  return `meta_${id.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}

function readMeta(metaPath: string): { title?: string; kind?: string } {
  if (!existsSync(metaPath)) return {};
  try {
    const meta = JSON.parse(readFileSync(metaPath, "utf8"));
    return { title: meta?.plan?.title, kind: meta?.kind };
  } catch {
    return {};
  }
}

const entries: Entry[] = [];
let skipped = 0;

if (existsSync(COMPOSITIONS_DIR)) {
  for (const id of readdirSync(COMPOSITIONS_DIR)) {
    const dir = join(COMPOSITIONS_DIR, id);
    const tsx = join(dir, "Composition.tsx");
    if (!statSync(dir).isDirectory() || !existsSync(tsx)) continue;

    // Remotion composition IDs allow letters, numbers, and hyphens. A few
    // older local scratch outputs used underscores; skip them instead of
    // generating a Studio entry that fails at runtime.
    if (!REMOTION_ID_RE.test(id)) {
      skipped += 1;
      continue;
    }

    const { title, kind } = readMeta(join(dir, "meta.json"));
    entries.push({
      id,
      alias: safeAlias(id),
      importPath: `../.compositions/${id}/Composition`,
      mtimeMs: statSync(tsx).mtimeMs,
      title,
      kind,
    });
  }
}

entries.sort((a, b) => b.mtimeMs - a.mtimeMs);

const banner = `// AUTO-GENERATED by scripts/generate-compositions-registry.ts.
// Run \`bun scripts/generate-compositions-registry.ts\` to refresh.
// Do not edit by hand.
`;

const importLines = entries
  .map((entry) => `import { compositionMeta as ${entry.alias} } from "${entry.importPath}";`)
  .join("\n");

const fallbackType = `{
  id: string;
  component: React.FC;
  width: number;
  height: number;
  fps: number;
  durationInFrames: number;
}`;

const metaType = entries[0] ? `typeof ${entries[0].alias}` : fallbackType;

const arrayBody = entries
  .map((entry) =>
    `  { meta: ${entry.alias}, title: ${JSON.stringify(entry.title ?? null)}, kind: ${JSON.stringify(entry.kind ?? null)} },`
  )
  .join("\n");

const out = `${banner}
export interface GeneratedCompositionEntry {
  meta: ${metaType};
  title: string | null;
  kind: string | null;
}

${importLines}

export const GENERATED_COMPOSITIONS: GeneratedCompositionEntry[] = [
${arrayBody}
];
`;

writeFileSync(OUTPUT, out);
console.log(
  `[gen-comp-registry] Wrote ${entries.length} ${entries.length === 1 ? "entry" : "entries"}${skipped ? `, skipped ${skipped} invalid id${skipped === 1 ? "" : "s"}` : ""} -> ${OUTPUT.replace(`${ROOT}/`, "")}`,
);
