#!/usr/bin/env bun
// Scans .compositions/<id>/Composition.tsx and writes src/_generated-compositions.ts.
// Run before `remotion studio` / `remotion render` so all generated compositions
// show up in the main Studio (organized into a Generated folder in Root.tsx).

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const COMPOSITIONS_DIR = join(ROOT, ".compositions");
const OUTPUT = join(ROOT, "src", "_generated-compositions.ts");

interface Entry {
  id: string;
  alias: string;
  importPath: string;
  mtimeMs: number;
  title?: string;
  kind?: string;
}

function safeAlias(id: string): string {
  return `meta_${id.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}

function readMeta(metaPath: string): { title?: string; kind?: string } {
  if (!existsSync(metaPath)) return {};
  try {
    const meta = JSON.parse(readFileSync(metaPath, "utf8"));
    return { title: meta?.plan?.title, kind: meta?.kind };
  } catch {
    return {};
  }
}

const entries: Entry[] = existsSync(COMPOSITIONS_DIR)
  ? readdirSync(COMPOSITIONS_DIR)
      .filter((name) => {
        const dir = join(COMPOSITIONS_DIR, name);
        return (
          statSync(dir).isDirectory() &&
          existsSync(join(dir, "Composition.tsx"))
        );
      })
      .map((id) => {
        const dir = join(COMPOSITIONS_DIR, id);
        const tsx = join(dir, "Composition.tsx");
        const { title, kind } = readMeta(join(dir, "meta.json"));
        return {
          id,
          alias: safeAlias(id),
          importPath: `../.compositions/${id}/Composition`,
          mtimeMs: statSync(tsx).mtimeMs,
          title,
          kind,
        };
      })
  : [];

// Newest first — most-recent renders show at the top of the Studio sidebar.
entries.sort((a, b) => b.mtimeMs - a.mtimeMs);

const banner = `// AUTO-GENERATED by scripts/generate-compositions-registry.ts.
// Run \`bun scripts/generate-compositions-registry.ts\` to refresh.
// Do not edit by hand.
`;

const importLines = entries
  .map((e) => `import { compositionMeta as ${e.alias} } from "${e.importPath}";`)
  .join("\n");

const fallbackType = `{
  id: string;
  component: React.FC;
  width: number;
  height: number;
  fps: number;
  durationInFrames: number;
}`;

const metaType = entries[0] ? `typeof ${entries[0].alias}` : fallbackType;

const arrayBody = entries
  .map(
    (e) =>
      `  { meta: ${e.alias}, title: ${JSON.stringify(
        e.title ?? null
      )}, kind: ${JSON.stringify(e.kind ?? null)} },`
  )
  .join("\n");

const out = `${banner}
export interface GeneratedCompositionEntry {
  meta: ${metaType};
  title: string | null;
  kind: string | null;
}

${importLines}

export const GENERATED_COMPOSITIONS: GeneratedCompositionEntry[] = [
${arrayBody}
];
`;

writeFileSync(OUTPUT, out);
console.log(
  `[gen-comp-registry] Wrote ${entries.length} ${
    entries.length === 1 ? "entry" : "entries"
  } → ${OUTPUT.replace(ROOT + "/", "")}`
);
